### ISSUE TITLE
Implementation of (Action|Bound)Scope

### ISSUE THREAD

**Issue by JustNrik** [JustNrik/NetUtilities#10]
### ActionScope and BoundScope

These types provides a scope in which an action is executed and then it will be undo in the end of the scope.

Usage example of ActionScope:

```cs
var foo = new Foo();
using (ActionScope<Foo>.Create(foo, x => x.Value = 1337, x => x.Value = 0))
    Console.WriteLine(foo.Value); // prints 1337

Console.WriteLine(foo.Value); // prints 0
```
Usage example of BoundScope:
```cs
Console.ForegroundColor = ConsoleColor.White;
using (BoundScope.Create(() => Console.ForegroundColor, ConsoleColor.Blue))
{
    Console.WriteLine("Hello in blue!");
}
Console.WriteLine("Hello in white!");
```

### Remarks

The main difference from `ActionScope` and `BoundScope` is that a `BoundScope` stores the old value of an object's property/field and assigns the new value, then, when the scope is disposed, the old value is reassigned. `ActionScope` represents an arbitrary action defined by the user.

### Help Wanted

I want to make tests to ensure it works as intended and make optimizations if needed.

**Comment by drake1011** [comment]
I'll take this
