### ISSUE TITLE
Wanna contribute to your library but can't enable the preview features in c#

### ISSUE THREAD

**Issue by gauravk97** [JustNrik/NetUtilities#11]
Hi,
Can I contribute to the Library? It seems small enough for me to practice my C# skills while learning latest language features at the same time. 

I tried to build the solution in VS2019 but I'm getting the error which says : To use preview language feature, select preview language version. On StackOverflow, it was recommended to add some lines to csproj file. 

https://stackoverflow.com/questions/53633538/how-to-enable-nullable-reference-types-feature-of-c-sharp-8-0-for-the-whole-proj

```
<PropertyGroup>
  ...
  <NullableReferenceTypes>true</NullableReferenceTypes>
  <LangVersion>8.0</LangVersion>
</PropertyGroup>

```
These lines were already there in csproj file of this solution. Any help?

**Comment by JerrettDavis** [comment]
Do you have the latest version of Visual Studio installed along with .Net Core 2.1 or 2.2?

**Comment by JustNrik** [comment]
You need the latest .NET Core SDK (3 preview6), you can get it here: https://dotnet.microsoft.com/download/dotnet-core/3.0
