### ISSUE TITLE
Create Wiki

### ISSUE THREAD

**Issue by joro550** [JustNrik/NetUtilities#15]
So you can more effectively document the utilities that you are providing.

**Comment by JustNrik** [comment]
I definitely will, it will take some time though 😅

**Comment by ssimontis** [comment]
@JustNrik How are you progressing with this? I am interested in taking it over if you need assistance. My plan would be to create XMLDoc comments for all methods which include examples showing their usage, extract the comment data, and then transform it into something prettier looking for the wiki.

**Comment by JustNrik** [comment]
I totally forgot this, I've been busy in the college and I'm currently on final exams. You are free to take over, would be greatly appreciated!

**Comment by joro550** [comment]
@JustNrik That would be great! I believe we do need you to create the wiki repository, if you go to the Wiki tab and click the "create the first page" button it will create a repository for the wiki that people can contrib to :)

**Comment by JustNrik** [comment]
> 
> 
> @JustNrik That would be great! I believe we do need you to create the wiki repository, if you go to the Wiki tab and click the "create the first page" button it will create a repository for the wiki that people can contrib to :)

Done :P

**Comment by joro550** [comment]
Awesome, will close down this ticket 👍
