### ISSUE TITLE
Implementation of Mapper

### ISSUE THREAD

**Issue by JustNrik** [JustNrik/NetUtilities#19]
### Mapper

This type is a wrapper over System.Type to provide high performance runtime manipulation on the given type, for example, getting/setting the value of a property without the expensive cost of reflection using the magic of Linq.Expressions. Also, each type will contain some metadata such as attributes.

### Help Wanted

Currently, I need to do major tests and add more features for more runtime manipulation. Any contribution/review is appreciated. Since this class makes a lot of one-time reflection calls, it want to keep it as lazy as possible, since not everyone will use every single member of this class so the allocation cost is lowered.

**Comment by AFM-Horizon** [comment]
Hey mate, I'll Jump onto this and write some more tests for the mapper class!
