### ISSUE TITLE
Implementation of MutableString

### ISSUE THREAD

**Issue by JustNrik** [JustNrik/NetUtilities#8]
### MutableString

This type is nothing but a wrapper of StringBuilder class. The focus of this class is to improve string manipulation and provide more utilities that StringBuilder doesn't offer.

### Help Wanted

Currently, I need to do major test to ensure everything works as intended, as well as make as many optimizations as possible. Suggestions for new members (properties/methods) into MutableStrings and tweaks in the current members are welcome as well.

**Comment by adlucio87** [comment]
Hi met, i will contribute to this issue. 
I did some test and fixed tow method: Contains for a string and EndsWith for string.

**Comment by Divij97** [comment]
Hi, can I contribute to this issue ?

**Comment by JustNrik** [comment]
> 
> 
> Hi, can I contribute to this issue ?

Hello, yes. Any contribution is always welcome!
