### ISSUE TITLE
Implementation of (U)Int24

### ISSUE THREAD

**Issue by JustNrik** [JustNrik/NetUtilities#9]
### Int24 / UInt24 Types

These types are for representing 24 bits integers for some use cases, a common example would be the representation of an RGB Color.

### Help Wanted

I need to test if the types are working properly and make as many optimizations as possible to make them as performant as possible.

**Comment by Emzi0767** [comment]
You will never achieve primitive type-grade performance, and the whole idea on its own is kinda questionable. If you need a 24-bit integer, why not just use a 32-bit integer, and clip it when needed?

**Comment by JustNrik** [comment]
> 
> 
> You will never achieve primitive type-grade performance, and the whole idea on its own is kinda questionable. If you need a 24-bit integer, why not just use a 32-bit integer, and clip it when needed?

About the performance, yea it's true. About using a 32-bit integer instead, well, there are use cases where you may need 24-bit integer and it's easier to work with it besides the cost of not being a primitive. For example, if you wanted the complement of it for some arithmethic, `~value` is nicer to work than `(~value & 0xFFFFFF)` or `(~value & 0x7FFFFF)`, also, I've seen repos that uses (U)Int24 for packet writing/reading (I've even seen 48bits one in some rare cases as well), it may be useful for someone. Just saying.
